

# =====================================================
#jrc18sia_motion_planner:

# MoveIt Configuration
position_tolerance : 0.01 # 1 cm
orientation_tolerance : 0.02 # 0.573 * 2 deg
planning_time : 1.0 # second
max_vel_scale_factor : 1.0
planning_attempts : 1
planning_id : 'RRTConnectkConfigDefault'

# MoveIt computeCartesianPath
jump_threshold : 2.0

# trajectory processing configuration
trajectory_velocity_scaling : 1.0

# evaluate the plan trajectory
max_plan_steps : 30
max_cartesion_plan_steps : 120

# Debug setting
debug_print : True # Print some useful infomation to check
confirm_act : True # true : You must input 'n' to confirm; false : Valid plan will be executed automatically

